water/waterflow/water/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('home/', home_view, name='home'),
    path('logout/', logout_view, name='logout'),  #  # Redirect to 'login' after logout
    path('about/', about_view, name='about'),
    path('network/', network_visualization, name='network_visualization'),
    path('network_management/', network_management, name='network_management'),
    path('create_node/', create_node, name='create_node'),
    path('create_edge/', create_edge, name='create_edge'),
    path('edit_node/<int:node_id>/', edit_node, name='edit_node'),
    path('edit_edge/<int:edge_id>/', edit_edge, name='edit_edge'),
    path('delete_node/<int:node_id>/', delete_node, name='delete_node'),
    path('delete_edge/<int:edge_id>/', delete_edge, name='delete_edge'),
    path('optimization/', optimization_page, name='optimization_page'),
    path('contact-us/', contact_us, name='contact_us'),
]

water/waterflow/waterflow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('water.urls')),  # Include URLs from `myapp`
]

water/waterflow/water/models.py
from django.db import models

class Node(models.Model):
    NODE_TYPE_CHOICES = [
        ('tank', 'Tank'),
        ('valve', 'Valve'),
        ('outlet', 'Outlet'),
        # Add other types as needed
    ]
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices=NODE_TYPE_CHOICES, default='tap')
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name

class Edge(models.Model):
    source = models.ForeignKey(Node, related_name='source', on_delete=models.CASCADE)
    target = models.ForeignKey(Node, related_name='target', on_delete=models.CASCADE)
    length = models.FloatField()
    flow_rate = models.FloatField()

    def __str__(self):
        return f'{self.source.name} -> {self.target.name}'
    
class NetworkComponent(models.Model):
    name = models.CharField(max_length=100)
    component_type = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

water/waterflow/water/forms.py
from django import forms
from .models import NetworkComponent, Edge, Node


class NetworkComponentForm(forms.ModelForm):
    class Meta:
        model = NetworkComponent
        fields = ['name', 'component_type', 'description']
        
class NodeForm(forms.ModelForm):
    class Meta:
        model = Node
        fields = ['name', 'type', 'latitude', 'longitude']
        widgets = {
            'type': forms.Select(choices=Node.NODE_TYPE_CHOICES),
        }

class EdgeForm(forms.ModelForm):
    class Meta:
        model = Edge
        fields = ['source', 'target', 'flow_rate']

        # Custom labels (if you want to customize the labels of the form fields)
        labels = {
            'source': 'Source Node',
            'target': 'Target Node',
            'flow_rate': 'Flow Rate',
        }

        # Help texts (if you want to provide any help texts for the form fields)
        help_texts = {
            'source': 'Select the source node from the list.',
            'target': 'Select the target node from the list.',
            'flow_rate': 'Enter the flow rate for the edge.',
        }

    # Custom validation to ensure that source and target nodes are not the same
    def clean(self):
        cleaned_data = super().clean()
        source = cleaned_data.get('source')
        target = cleaned_data.get('target')

        # Ensure the source and target nodes are not the same
        if source.type == 'outlet':
            raise forms.ValidationError('Outlet cannot be selected.')
        
        if target.type == 'tank':
            raise forms.ValidationError('Tank (source) cannot be a internal node')
        
        if source == target:
            raise forms.ValidationError('Source and target nodes cannot be the same.')

        return cleaned_data

class OptimizationForm(forms.Form):
    # Choices for optimization algorithms
    algorithm_choices = [
        #('dijkstra', 'Dijkstra'),
        ('edmonds_karp', 'Edmonds-Karp'),
        ('ford_fulkerson', 'Ford-Fulkerson'),
        ('dinic', 'Dinic'),
        ('push_relabel', 'Push-Relabel')
        #('simplex', 'Simplex')
    ]
    
    # Form fields
    algorithm = forms.ChoiceField(choices=algorithm_choices, label="Optimization Algorithm")
    source_node = forms.ModelChoiceField(
        queryset=Node.objects.all(),
        label="Source Node",
        required=True
    )
    target_node = forms.ModelChoiceField(
        queryset=Node.objects.all(),
        label="Target Node",
        required=True
    )
    
    
    
    # Clean method to validate the form data
    def clean(self):
        cleaned_data = super().clean()
        source = cleaned_data.get('source_node')
        target = cleaned_data.get('target_node')

        # Check if the source and target nodes are the same
        if source.type != 'tank':
            raise forms.ValidationError("The source should be a Tank")
        if target.type == 'tank' or target.type == 'valve':
            raise forms.ValidationError("The target must me an outlet")
        if source == target:
            raise forms.ValidationError(
                "Source and Target nodes cannot be the same."
            )

        return cleaned_data

water/waterflow/water/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse ,reverse_lazy
from django.http import JsonResponse
from django.core import serializers
from django.views import View

import json
import math
import time

from .forms import *
from .models import *
from .algorithms import *


def register_view(request):
    # Check if the request method is POST
    if request.method == 'POST':
        # Instantiate the UserCreationForm with POST data
        form = UserCreationForm(request.POST)
        
        # Check if the form is valid
        if form.is_valid():
            # Save the user form and get the new user object
            new_user = form.save()
            
            # Automatically log in the user
            login(request, new_user)
            
            # Display a success message (optional)
            messages.success(request, 'Registration successful! You are now logged in.')
            
            # Redirect the user to the desired URL after registration
            return redirect('home')  # Redirect to your desired page
            
        else:
            # Display error messages if the form is invalid (optional)
            messages.error(request, 'Registration failed. Please check the form for errors.')
    
    else:
        # If the request method is GET, instantiate a blank UserCreationForm
        form = UserCreationForm()
    
    # Render the registration form template with the form context
    return render(request, 'register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def home_view(request):
    return render(request, 'home.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')  # Change 'home' to your actual home page URL
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

@login_required
def about_view(request):
    return render(request, 'about.html')

@login_required
def network_visualization(request):
    # Fetch data from the models
    nodes = Node.objects.all()
    edges = Edge.objects.all()

    # Prepare data for D3.js visualization
    node_data = [{'id': node.id, 'name': node.name, 'type': node.type, 'lat': node.latitude, 'lon': node.longitude} for node in nodes]
    edge_data = [{'source': edge.source.id, 'target': edge.target.id, 'length': edge.length, 'flow_rate': edge.flow_rate} for edge in edges]

    # Convert data to JSON format for use in the JavaScript frontend
    network_data = {
        'nodes': node_data,
        'edges': edge_data
    }
    network_data_json = json.dumps(network_data)

    # Render the template and pass the data as context
    return render(request, 'network_visualization.html', {
        'network_data_json': network_data_json
    })

@login_required
def network_management(request):
    # View for the network management page
    nodes = Node.objects.all()
    edges = Edge.objects.all()
    
    # Handle search/filtering if needed
    # Add logic to search/filter nodes and edges
    
    context = {
        'nodes': nodes,
        'edges': edges
    }
    return render(request, 'network_management.html', context)

@login_required
def create_node(request):
    # View to handle node creation
    if request.method == 'POST':
        form = NodeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Node created successfully.')
            return redirect(reverse('network_management'))
    else:
        form = NodeForm()
    return render(request, 'create_node.html', {'form': form})

# Function to calculate distance between two points using the Haversine formula
def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of the Earth in kilometers
    dLat = math.radians(lat2 - lat1)
    dLon = math.radians(lon2 - lon1)
    a = (math.sin(dLat / 2) ** 2 +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dLon / 2) ** 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

def euclidean_distance(lat1, lon1, lat2, lon2):
    # Calculate the distance using the Euclidean distance formula
    distance = ((lat2 - lat1) ** 2 + (lon2 - lon1) ** 2) ** 0.5
    return distance

@login_required
def create_edge(request):
    # Fetch all available nodes to display in the dropdown
    nodes = Node.objects.all()
    
    if request.method == 'POST':
        form = EdgeForm(request.POST)
        if form.is_valid():
            edge = form.save(commit=False)
            
            # Check if an edge already exists between the selected source and target nodes
            source_node_id = form.cleaned_data['source'].id
            target_node_id = form.cleaned_data['target'].id
            
            existing_edge = Edge.objects.filter(source_id=source_node_id, target_id=target_node_id).exists()
            if existing_edge:
                messages.error(request, 'Edge already exists between these nodes.')
                return redirect('create_edge')  # Redirect back to the edge creation page
            
            # Calculate length based on latitudes and longitudes of source and target nodes
            source = get_object_or_404(Node, pk=source_node_id)
            target = get_object_or_404(Node, pk=target_node_id)
            
            # Calculate the Euclidean distance
            length = euclidean_distance(source.latitude, source.longitude, target.latitude, target.longitude)
            edge.length = length  # Update the length field
            
            edge.save()  # Save the edge with the updated length
            messages.success(request, 'Edge created successfully.')
            
            return redirect('network_visualization')  # Redirect to the visualization page
    else:
        form = EdgeForm()

    return render(request, 'create_edge.html', {
        'form': form,
        'nodes': nodes,  # Pass the list of nodes to the template
    })

@login_required
def edit_node(request, node_id):
    # View to handle node editing
    node = get_object_or_404(Node, id=node_id)
    if request.method == 'POST':
        form = NodeForm(request.POST, instance=node)
        if form.is_valid():
            form.save()
            messages.success(request, 'Node updated successfully.')
            return redirect(reverse('network_management'))
    else:
        form = NodeForm(instance=node)
    return render(request, 'edit_node.html', {'form': form})

@login_required
def edit_edge(request, edge_id):
    # View to handle edge editing
    edge = get_object_or_404(Edge, id=edge_id)
    if request.method == 'POST':
        form = EdgeForm(request.POST, instance=edge)
        
        if form.is_valid():
            edge = form.save(commit=False)
            # Calculate length based on latitudes and longitudes of source and target nodes
            source = edge.source
            target = edge.target
            length = euclidean_distance(source.latitude, source.longitude, target.latitude, target.longitude)
            edge.length = length  # Update the length field
            edge.save()  # Save the edge with the updated length
            form.save()
            messages.success(request, 'Edge updated successfully.')
            return redirect(reverse('network_management'))
    else:
        form = EdgeForm(instance=edge)
    return render(request, 'edit_edge.html', {'form': form})

@login_required
def delete_node(request, node_id):
    # View to handle node deletion
    node = get_object_or_404(Node, id=node_id)
    node.delete()
    messages.success(request, 'Node deleted successfully.')
    return redirect(reverse('network_management'))

@login_required
def delete_edge(request, edge_id):
    # View to handle edge deletion
    edge = get_object_or_404(Edge, id=edge_id)
    edge.delete()
    messages.success(request, 'Edge deleted successfully.')
    return redirect(reverse('network_management'))

class CreateNodeView(View):
    def get(self, request):
        form = NodeForm()
        return render(request, 'node_form.html', {'form': form})
    
    def post(self, request):
        form = NodeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')  # Redirect to home page or network visualization page
        
        return render(request, 'node_form.html', {'form': form})

class CreateEdgeView(View):
    def get(self, request):
        form = EdgeForm()
        return render(request, 'edge_form.html', {'form': form})
    
    def post(self, request):
        form = EdgeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')  # Redirect to home page or network visualization page
        
        return render(request, 'edge_form.html', {'form': form})

def get_network_data(request):
    # Fetch nodes and edges from the database
    nodes = Node.objects.all()
    edges = Edge.objects.all()

    # Serialize nodes and edges
    nodes_json = serializers.serialize('json', nodes)
    edges_json = serializers.serialize('json', edges)

    # Convert data to JSON
    network_data = {
        'nodes': nodes_json,
        'edges': edges_json
    }

    return JsonResponse(network_data)

def construct_graph_from_db():
    from .models import Edge

water/waterflow/water/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #00ffff; /* Body background color */
            color: black; /* Text color */
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        #header {
            background-color: black; /* Header background color */
            color: #00ffff; /* Header text color */
            padding: 20px 0;
            width: 100%;
            position: fixed;
            top: 0;
            z-index: 1000;
            text-align: center;
        }

        #container {
            background-color: #fff; /* Content background color */
            padding: 80px 30px 30px; /* Adjust padding to give space for the fixed header */
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 255, 255, 0.5);
            max-width: 90%;
            margin-top: 100px;
        }

        h1 {
            margin-bottom: 20px;
            font-size: 2em;
        }

        p {
            margin-bottom: 10px;
            font-size: 1.5em;
            font-weight: bold;
        }

        ul {
            list-style-type: none;
            padding-left: 20px;
        }

        li {
            margin-bottom: 15px;
            font-size: 1.1em;
        }

        li::before {
            content: "•"; /* Bullet symbol */
            display: inline-block;
            width: 1em;
            margin-left: -1em;
            margin-right: 10px;
        }

        .back-button {
            display: block;
            text-align: center;
            margin-top: 30px;
        }

        .back-button a {
            text-decoration: none;
            color: #00ffff;
            background-color: black;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .back-button a:hover {
            background-color: rgba(0, 255, 255, 0.5);
            color:black;
        }
    </style>
</head>
<body>
    <div id="header">
        <h1>About Our Website</h1>
    </div>
    <div id="container">
        <p>Welcome to our website! Here's some information about how it works:</p>
        <ul>
            <li><strong>Functionality:</strong> Our website is designed to manage water flow networks. Users can create and visualize networks, optimize flow, and perform various network management tasks.</li>
            <li><strong>Interacting with the Website:</strong> Users can create nodes and edges to represent points and connections in the network. They can also perform optimization tasks to find the most efficient flow paths.</li>
            <li><strong>Conditions for Edges:</strong> Edges represent connections between nodes in the network. They must have a valid source and target node, as well as a flow rate indicating the amount of water that can flow through them.The tank node cannot be selected as a target as it is the source. The outlet Type node cannot be selected as a source as it is the end point of the water network ie.taps. The valve Node acts as connecting internal nodes in the network.</li>
            <li><strong>Optimization:</strong> Our website offers optimization algorithms such as Edmonds-Karp, Ford-Fulkerson, Dinic, and Push-Relabel to find the maximum flow in the network. Users can visualize the optimized flow paths to understand the network's efficiency.</li>
        </ul>
        <div class="back-button">
            <a href="{% url 'home' %} ">Back to Home</a>
        </div>
    </div>
    
</body>
</html>

water/waterflow/water/templates/contact_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: black;
            color: #00ffff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            width: 50%;
            margin: 0 auto;
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        input[type="text"],
        input[type="email"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }

        textarea {
            height: 150px;
        }

        button[type="submit"] {
            background-color: #00ffff;
            color: black;
            border: none;
            padding: 15px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            font-weight: bold;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Contact Us</h1>
    <form method="post">
        {% csrf_token %}
        <label for="name">Your Name:</label>
        <input type="text" id="name" name="name" required>
        <label for="email">Your Email:</label>
        <input type="email" id="email" name="email" required>
        <label for="message">Message:</label>
        <textarea id="message" name="message" required></textarea>
        <button type="submit">Send Message</button>
    </form>
</body>
</html>

water/waterflow/water/templates/create_edge.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Edge</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #00ffff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            background-color: black;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 400px;
            display: inline-block;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #00ffff;
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
            display: block;
            color: #00ffff
        }

        select,
        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
            text-align: center;
        }
        
        button[type="submit"] {
            background-color: #00ffff;
            color: black;
            border: none;
            margin-top: 20px;
            padding: 15px 20px;
            border-radius: 50px;
            cursor: pointer;
            font-size: 18px;
            font-weight: bold;
            width: 100%;
            display: block;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        p {
            margin-top: 20px;
            text-align: center;
        }

        a {
            color: #00ffff;
            text-decoration: none;
            font-weight: bold;
            font-size: 18px;
        }

        a:hover {
            text-decoration: underline;
        }
        .error {
            color: #dc3545; /* Red error message */
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <form method="POST" action="{% url 'create_edge' %}">
        {% csrf_token %}
        <h1>Create Edge</h1>
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}

        <div>
            <label for="source">Source Node:</label>
            <select name="source" id="source" required>
                {% for node in nodes %}
                <option value="{{ node.id }}">{{ node.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="target">Target Node:</label>
            <select name="target" id="target" required>
                {% for node in nodes %}
                <option value="{{ node.id }}">{{ node.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="flow_rate">Flow Rate:</label>
            <input type="number" step="any" name="flow_rate" id="flow_rate" required>
        </div>

        <div>
            <button type="submit">Create Edge</button>
        </div>
        <p><a href="{% url 'network_management' %}">Back</a></p>
    </form>
    {% if error_message %}
        <div class="error">
            <strong>Error:</strong> {{ error_message }}
        </div>
    {% endif %}
</body>

</html>

water/waterflow/water/templates/create_node.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Node</title>
    <!-- Add any additional CSS for styling the page -->
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #00ffff; /* Light gray background */
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            background-color: black; /* White background */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 400px;
            display: inline-block;
            margin-top: 30px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            padding-top: 10px;
            color: #00ffff; /* Blue heading */
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
            display: block;
            color: #00ffff; /* Dark gray text */
        }

        select,
        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ced4da; /* Gray border */
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }

        button[type="submit"] {
            background-color: #00ffff;
            color: black;
            border: none;
            margin-top: 20px;
            padding: 15px 20px;
            border-radius: 50px;
            cursor: pointer;
            font-size: 18px;
            font-weight: bold;
            width: 100%;
            display: block;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        p {
            margin-top: 20px;
            text-align: center;
            color: #007bff; /* Blue link */
        }

        a {
            color: #00ffff;
            text-decoration: none;
            font-weight: bold;
            font-size: 18px;
        }

        a:hover {
            text-decoration: underline;
        }
        .error {
            color: #dc3545; /* Red error message */
            margin-top: 20px;
        }
    </style>
    
</head>
<body>
    <div>
        
    </div>
    <div>
        
    <!-- Form for creating a new node -->
        <form method="post" action="{% url 'create_node' %}">
            

            <h1>Create Node</h1>
            {% csrf_token %}
                
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
            <!-- Name field -->
            <div>
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" name="name" required>
            </div>

            <!-- Latitude field -->
            <div>
                <label for="id_latitude">Latitude:</label>
                <input type="number" step="0.0001" id="id_latitude" name="latitude" required>
            </div>

            <!-- Longitude field -->
            <div>
                <label for="id_longitude">Longitude:</label>
                <input type="number" step="0.0001" id="id_longitude" name="longitude" required>
            </div>

            <!-- Type dropdown menu -->
            <div>
                <label for="id_type">Type:</label>
                <select id="id_type" name="type" required>
                    <option value="tank">Tank</option>
                    <option value="valve">Valve</option>
                    <option value="outlet">Outlet</option>
                    <!-- Add other types as needed -->
                </select>
            </div>

            <!-- Submit button -->
            <div>
                <button type="submit">Create Node</button>
            </div>
            <p><a href="{% url 'network_management' %}">Back</a></p>
        </form>
        </div>
        {% if error_message %}
            
            <div class="error">
                <strong>Error:</strong> {{ error_message }}
           </div>
        {% endif %}

    <!-- Link to go back to the previous page or the main page -->
    
</body>
</html>